(()=>{const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const DEMO_BOOKINGS=[
{id:1001,name:'Laura Gómez',phone:'34600111222',email:'laura.demo@email.com',service:'Gel Builder',date:'2026-10-10',time:'Tarde',message:'Querría un acabado nude con un detalle dorado.',status:'new',createdAt:'2026-10-07T12:20:00.000Z'},
{id:1002,name:'Marta Ruiz',phone:'34600222333',email:'marta.demo@email.com',service:'Manicura rusa',date:'2026-10-11',time:'Mañana',message:'Es mi primera vez. Busco un acabado natural.',status:'confirmed',createdAt:'2026-10-06T18:40:00.000Z'},
{id:1003,name:'Andrea López',phone:'34600333444',email:'andrea.demo@email.com',service:'Nail Art',date:'2026-10-14',time:'Tarde',message:'Tengo una referencia de diseño y puedo enviarla por WhatsApp.',status:'new',createdAt:'2026-10-07T09:15:00.000Z'},
{id:1004,name:'Nerea García',phone:'34600444555',email:'nerea.demo@email.com',service:'Pedicura SPA',date:'2026-10-16',time:'Mediodía',message:'Preferiría una cita sobre las 13:00 si fuera posible.',status:'archived',createdAt:'2026-10-05T16:05:00.000Z'}];
let data=window.MikyCMS.get();
if(!localStorage.getItem('miky_admin_data')) window.MikyCMS.set(data);
if(!localStorage.getItem('miky_bookings')) localStorage.setItem('miky_bookings',JSON.stringify(DEMO_BOOKINGS));
const save=()=>{window.MikyCMS.set(data);$('#saved').textContent='Guardado';setTimeout(()=>$('#saved').textContent='Todo guardado',800)};
const bookings=()=>{try{return JSON.parse(localStorage.getItem('miky_bookings')||'[]')}catch{return[]}};
const setBookings=a=>localStorage.setItem('miky_bookings',JSON.stringify(a));
const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)};
const titles={dashboard:'Resumen',bookings:'Solicitudes',services:'Servicios',gallery:'Galería',training:'Formación',reviews:'Reseñas',faqs:'FAQs',contact:'Contacto'};
function show(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+v));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#title').textContent=titles[v];render()}
$$('#nav button').forEach(b=>b.onclick=()=>show(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
function renderDash(){const b=bookings(),n=b.filter(x=>x.status==='new').length,c=b.filter(x=>x.status==='confirmed').length;$('#badge').textContent=n;$('#metrics').innerHTML=`<div class="metric"><span>Nuevas solicitudes</span><b>${n}</b></div><div class="metric"><span>Citas confirmadas</span><b>${c}</b></div><div class="metric"><span>Servicios activos</span><b>${data.services.filter(x=>x.visible!==false).length}</b></div><div class="metric"><span>Fotos publicadas</span><b>${data.gallery.filter(x=>x.visible!==false).length}</b></div>`;const recent=$('#recentBookings');if(recent)recent.innerHTML=b.slice(0,4).map(x=>`<div class="mini-booking"><div><b>${esc(x.name)}</b><span>${esc(x.service)} · ${esc(x.date||'Sin fecha')}</span></div><i class="status ${x.status}">${x.status==='new'?'Nueva':x.status==='confirmed'?'Confirmada':'Archivada'}</i></div>`).join('')}
function renderBookings(){let arr=bookings();const q=($('#bookingSearch')?.value||'').toLowerCase(),f=$('#bookingFilter')?.value||'all';if(q)arr=arr.filter(x=>(x.name+' '+x.service+' '+x.phone+' '+x.email).toLowerCase().includes(q));if(f!=='all')arr=arr.filter(x=>x.status===f);$('#bookings').innerHTML=arr.map(x=>`<article class="booking"><div><div class="booking-head"><b>${esc(x.name||'Sin nombre')} · ${esc(x.service||'Consulta')}</b><i class="status ${x.status}">${x.status==='new'?'Nueva':x.status==='confirmed'?'Confirmada':'Archivada'}</i></div><span>${esc(x.phone||'')} · ${esc(x.email||'Sin email')}</span><span>${esc(x.date||'Sin fecha')} · ${esc(x.time||'')}</span><small>${esc(x.message||'')}</small></div><div class="actions"><a class="primary btn" target="_blank" href="https://wa.me/${String(x.phone||'').replace(/\D/g,'')}?text=${encodeURIComponent('Hola '+(x.name||'')+', te escribimos desde Miky Nails Vitoria sobre tu solicitud de '+(x.service||'cita')+'.')}">WhatsApp</a><button class="ghost" data-confirm="${x.id}">Confirmar</button><button class="ghost" data-archive="${x.id}">Archivar</button><button class="danger" data-delbook="${x.id}">Eliminar</button></div></article>`).join('')||'<div class="panel">No hay solicitudes con ese filtro.</div>';
$$('[data-confirm]').forEach(b=>b.onclick=()=>changeBooking(+b.dataset.confirm,'confirmed'));$$('[data-archive]').forEach(b=>b.onclick=()=>changeBooking(+b.dataset.archive,'archived'));$$('[data-delbook]').forEach(b=>b.onclick=()=>{setBookings(bookings().filter(x=>x.id!=b.dataset.delbook));render();toast('Solicitud eliminada')})}
function changeBooking(id,status){const a=bookings(),x=a.find(v=>v.id===id);if(x)x.status=status;setBookings(a);render();toast(status==='confirmed'?'Cita confirmada':'Solicitud archivada')}
$('#bookingSearch')?.addEventListener('input',renderBookings);$('#bookingFilter')?.addEventListener('change',renderBookings);
function renderServices(){const g=$('#services');g.innerHTML=data.services.map(s=>`<article class="row-card"><div class="row-main"><img class="row-thumb" src="${attr(s.image)}" alt=""><div><h3>${esc(s.title)}</h3><p>${esc(s.category)} · ${esc(s.duration)} · ${esc(s.price)}</p><span class="visibility">${s.visible!==false?'Visible en web':'Oculto'}</span></div></div><div class="actions"><button class="ghost" data-es="${s.id}">Editar</button><button class="ghost" data-ts="${s.id}">${s.visible!==false?'Ocultar':'Mostrar'}</button><button class="danger" data-ds="${s.id}">Eliminar</button></div></article>`).join('');$$('[data-es]').forEach(b=>b.onclick=()=>editService(+b.dataset.es));$$('[data-ts]').forEach(b=>b.onclick=()=>{const s=data.services.find(x=>x.id==b.dataset.ts);s.visible=s.visible===false?true:false;save();render();toast('Visibilidad actualizada')});$$('[data-ds]').forEach(b=>b.onclick=()=>{data.services=data.services.filter(s=>s.id!=b.dataset.ds);save();render();toast('Servicio eliminado')})}
function editService(id){const s=id?data.services.find(x=>x.id===id):{id:Date.now(),title:'',desc:'',category:'Manicura',duration:'',price:'Consultar',image:'',visible:true};modal(`<h2>${id?'Editar':'Nuevo'} servicio</h2><div class="form-card"><label>Nombre<input id="s1" value="${attr(s.title)}"></label><label>Descripción<textarea id="s2">${esc(s.desc)}</textarea></label><div class="two"><label>Categoría<input id="s3" value="${attr(s.category)}"></label><label>Duración<input id="s4" value="${attr(s.duration)}"></label></div><label>Precio<input id="s5" value="${attr(s.price)}"></label><label>Imagen URL<input id="s6" value="${attr(s.image)}"></label><label>O subir imagen<input id="sfile" type="file" accept="image/*"></label><label class="check"><input id="s7" type="checkbox" ${s.visible!==false?'checked':''}> Visible en la web</label><button class="primary" id="saveModal">Guardar</button></div>`);$('#saveModal').onclick=async()=>{s.title=$('#s1').value;s.desc=$('#s2').value;s.category=$('#s3').value;s.duration=$('#s4').value;s.price=$('#s5').value;s.visible=$('#s7').checked;s.image=await imageValue($('#sfile').files[0],$('#s6').value||s.image);if(!id)data.services.push(s);save();close();render();toast('Servicio guardado')}}$('#addService').onclick=()=>editService();
function renderGallery(){const g=$('#gallery');g.innerHTML=data.gallery.map(x=>`<article class="media-card"><img src="${attr(x.image)}" alt=""><div class="body"><b>${esc(x.title)}</b><small>${esc(x.category)} · ${x.visible!==false?'Visible':'Oculta'}</small><div class="actions"><button class="ghost" data-eg="${x.id}">Editar</button><button class="ghost" data-tg="${x.id}">${x.visible!==false?'Ocultar':'Mostrar'}</button><button class="danger" data-dg="${x.id}">Eliminar</button></div></div></article>`).join('');$$('[data-eg]').forEach(b=>b.onclick=()=>editGallery(+b.dataset.eg));$$('[data-tg]').forEach(b=>b.onclick=()=>{const x=data.gallery.find(v=>v.id==b.dataset.tg);x.visible=x.visible===false?true:false;save();render();toast('Galería actualizada')});$$('[data-dg]').forEach(b=>b.onclick=()=>{data.gallery=data.gallery.filter(x=>x.id!=b.dataset.dg);save();render();toast('Imagen eliminada')})}
function editGallery(id){const x=id?data.gallery.find(v=>v.id===id):{id:Date.now(),title:'',category:'Manicura',image:'',visible:true};modal(`<h2>Imagen de galería</h2><div class="form-card"><label>Título<input id="g1" value="${attr(x.title)}"></label><label>Categoría<input id="g2" value="${attr(x.category)}"></label><label>Imagen URL<input id="g3" value="${attr(x.image)}"></label><label>O subir imagen<input id="gfile" type="file" accept="image/*"></label><label class="check"><input id="g4" type="checkbox" ${x.visible!==false?'checked':''}> Visible en la web</label><button class="primary" id="saveModal">Guardar</button></div>`);$('#saveModal').onclick=async()=>{x.title=$('#g1').value;x.category=$('#g2').value;x.visible=$('#g4').checked;x.image=await imageValue($('#gfile').files[0],$('#g3').value||x.image);if(!id)data.gallery.push(x);save();close();render();toast('Galería actualizada')}}$('#addGallery').onclick=()=>editGallery();
function renderTraining(){const t=data.training;$('#training').innerHTML=`<div class="training-main"><div class="form-card"><h3>Presentación</h3><label>Título<input id="tt" value="${attr(t.title)}"></label><label>Descripción<textarea id="td">${esc(t.desc)}</textarea></label><label>Imagen principal<input id="ti" value="${attr(t.image)}"></label><label>O subir imagen<input id="tfile" type="file" accept="image/*"></label><button class="primary" id="st">Guardar presentación</button></div><div class="training-preview"><img src="${attr(t.image)}"><div><b>${esc(t.title)}</b><span>${t.modules.length} módulos · formato 1:1</span></div></div></div><div class="modules">${t.modules.map(m=>`<article class="module-admin"><img src="${attr(m.image)}"><div class="body"><b>${esc(m.title)}</b><p>${esc(m.desc)}</p><div class="actions"><button class="ghost" data-em="${m.id}">Editar</button><button class="danger" data-dm="${m.id}">Eliminar</button></div></div></article>`).join('')}</div>`;$('#st').onclick=async()=>{t.title=$('#tt').value;t.desc=$('#td').value;t.image=await imageValue($('#tfile').files[0],$('#ti').value||t.image);save();render();toast('Formación guardada')};$$('[data-em]').forEach(b=>b.onclick=()=>editModule(+b.dataset.em));$$('[data-dm]').forEach(b=>b.onclick=()=>{t.modules=t.modules.filter(m=>m.id!=b.dataset.dm);save();render();toast('Módulo eliminado')})}
function editModule(id){const m=id?data.training.modules.find(x=>x.id===id):{id:Date.now(),title:'',desc:'',image:''};modal(`<h2>Módulo de formación</h2><div class="form-card"><label>Título<input id="m1" value="${attr(m.title)}"></label><label>Descripción<textarea id="m2">${esc(m.desc)}</textarea></label><label>Imagen URL<input id="m3" value="${attr(m.image)}"></label><label>O subir imagen<input id="mfile" type="file" accept="image/*"></label><button class="primary" id="saveModal">Guardar</button></div>`);$('#saveModal').onclick=async()=>{m.title=$('#m1').value;m.desc=$('#m2').value;m.image=await imageValue($('#mfile').files[0],$('#m3').value||m.image);if(!id)data.training.modules.push(m);save();close();render();toast('Módulo guardado')}}$('#addModule').onclick=()=>editModule();
function simple(kind,container,fields){const arr=data[kind];$(container).innerHTML=arr.map(x=>`<article class="row-card"><div><h3>${esc(x[fields[0]])}</h3><p>${esc(x[fields[1]])}</p></div><div class="actions"><button class="ghost" data-edit-simple="${kind}:${x.id}">Editar</button><button class="danger" data-del-simple="${kind}:${x.id}">Eliminar</button></div></article>`).join('');$$('[data-edit-simple]').forEach(b=>b.onclick=()=>editSimple(...b.dataset.editSimple.split(':')));$$('[data-del-simple]').forEach(b=>b.onclick=()=>{const [k,id]=b.dataset.delSimple.split(':');data[k]=data[k].filter(x=>x.id!=id);save();render();toast('Elemento eliminado')})}
function editSimple(kind,id){const review=kind==='reviews',arr=data[kind],x=id?arr.find(v=>v.id==id):review?{id:Date.now(),name:'',text:''}:{id:Date.now(),q:'',a:''};modal(`<h2>${review?'Reseña':'Pregunta frecuente'}</h2><div class="form-card"><label>${review?'Nombre':'Pregunta'}<input id="x1" value="${attr(review?x.name:x.q)}"></label><label>${review?'Texto':'Respuesta'}<textarea id="x2">${esc(review?x.text:x.a)}</textarea></label><button class="primary" id="saveModal">Guardar</button></div>`);$('#saveModal').onclick=()=>{if(review){x.name=$('#x1').value;x.text=$('#x2').value}else{x.q=$('#x1').value;x.a=$('#x2').value}if(!id)arr.push(x);save();close();render();toast('Contenido guardado')}}$('#addReview').onclick=()=>editSimple('reviews');$('#addFaq').onclick=()=>editSimple('faqs');
function renderContact(){const c=data.contact;$('#contact').innerHTML=`<div class="form-card"><label>Teléfono<input id="c1" value="${attr(c.phone)}"></label><label>WhatsApp<input id="c2" value="${attr(c.whatsapp)}"></label><label>Instagram<input id="c3" value="${attr(c.instagram)}"></label><label>Dirección<input id="c4" value="${attr(c.address)}"></label><button class="primary" id="sc">Guardar contacto</button></div>`;$('#sc').onclick=()=>{data.contact={phone:$('#c1').value,whatsapp:$('#c2').value,instagram:$('#c3').value,address:$('#c4').value};save();toast('Contacto guardado')}}
function render(){renderDash();const active=$('.view.active')?.id;if(active==='view-bookings')renderBookings();if(active==='view-services')renderServices();if(active==='view-gallery')renderGallery();if(active==='view-training')renderTraining();if(active==='view-reviews')simple('reviews','#reviews',['name','text']);if(active==='view-faqs')simple('faqs','#faqs',['q','a']);if(active==='view-contact')renderContact()}
$('#seedDemo').onclick=()=>{if(confirm('¿Restaurar los datos demo del panel?')){localStorage.removeItem('miky_admin_data');data=window.MikyCMS.defaults;window.MikyCMS.set(data);setBookings(DEMO_BOOKINGS);render();toast('Datos demo restaurados')}};
$('#exportData').onclick=()=>{const blob=new Blob([JSON.stringify({content:data,bookings:bookings()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='miky-nails-demo-backup.json';a.click();URL.revokeObjectURL(a.href)};
const modalEl=$('#modal');function modal(h){$('#modalBody').innerHTML=h;modalEl.classList.add('open')}function close(){modalEl.classList.remove('open')}$('#close').onclick=close;modalEl.onclick=e=>{if(e.target===modalEl)close()};
function imageValue(file,fallback){return new Promise(res=>{if(!file)return res(fallback);if(file.size>3.5*1024*1024){toast('La imagen es demasiado grande. Usa una menor de 3,5 MB.');return res(fallback)}const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file)})}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function attr(s=''){return esc(s)}
render()})();